services:
  aimbot:
    image: aimbot:1.0.0-openvino
    container_name: aimbot
    network_mode: host
    devices:
      # makcu_port
      - "/dev/ttyACM0:/dev/ttyACM0"
      # capture_device — only needed for source_stream = "elgato://"
      # - "/dev/video0:/dev/video0"
      # only needed for openvino_device_type = "GPU"
      # - "/dev/dri:/dev/dri"
    volumes:
      - ./assets:/app/assets
      - ./config.docker.toml:/app/config.toml:ro
    environment:
      - RUST_LOG=info,aimbot=info
