version: '3.7'
services:
  aimbot:
    image: aimbot:1.0.0
    container_name: aimbot
    network_mode: host
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    volumes:
      - ./assets:/app/assets
      - ./assets/best.onnx:/app/assets/best.onnx
    environment:
      - RUST_LOG=info,aimbot=info
      - EVENT_LISTENER_PORT=10000
      - SOURCE_STREAM=ndi://172.24.36.133
      - NDI_SOURCE_NAME=pc1
      - NDI_TIMEOUT=1000
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - REGION_LEFT=832
      - REGION_TOP=412
      - REGION_WIDTH=256
      - REGION_HEIGHT=256
      - SCALE_MIN_ZONE=0.85
      - SLEEP_INTERVAL_CAPTURE=2
      - MODEL_PROVIDER=CPU
      - MODEL_PATH=/app/assets/best.onnx
      - TRT_CACHE_DIR=/app/assets
      - MODEL_INPUT_SIZE=256
      - MODEL_CONF=0.7
      - MODEL_IOU=0.6
      - TRT_MIN_SHAPES=images:1x3x256x256
      - TRT_OPT_SHAPES=images:1x3x256x256
      - TRT_MAX_SHAPES=images:1x3x256x256
      - TRT_FP16=true
      - TRT_MAX_PARTITION_ITERATIONS=10
      - TRT_BUILDER_OPTIMIZATION_LEVEL=5
      - GPU_ID=0
      - GPU_MEM_LIMIT=2147483648
      - INTRA_THREADS=2
      - MAKCU_PORT=/dev/ttyACM0
      - MAKCU_BAUD=4000000
      - MOUSE_DPI=1000
      - GAME_SENS=1.0